export const DEFAULT_WORDS_PER_CAPTION = 3;
export const MIN_CAPTION_DURATION_SECONDS = 0.8;
export const DEFAULT_CAPTION_LINE_CHARACTERS = 13;
export const MIN_CAPTION_LINE_CHARACTERS = 1;
export const MAX_CAPTION_LINE_CHARACTERS = 30;
